-- Populate database with initial items (50 per equipment type)
USE twitch_rpg;

-- Boots (50 items)
INSERT INTO items (name, type, rarity, strength_bonus, agility_bonus, vitality_bonus, intelligence_bonus, value, special_effect) VALUES
-- Common Boots (20 items)
('Lederstiefel', 'boots', 'common', 0, 2, 1, 0, 100, NULL),
('Wanderstiefel', 'boots', 'common', 1, 1, 1, 0, 120, NULL),
('Kampfstiefel', 'boots', 'common', 2, 1, 0, 0, 110, NULL),
('Laufschuhe', 'boots', 'common', 0, 3, 0, 0, 100, NULL),
('Arbeitsstiefel', 'boots', 'common', 1, 0, 2, 0, 130, NULL),
('Stoffschuhe', 'boots', 'common', 0, 1, 0, 2, 95, NULL),
('Eisenstiefel', 'boots', 'common', 2, 0, 1, 0, 140, NULL),
('Schnellstiefel', 'boots', 'common', 0, 2, 1, 0, 105, NULL),
('Verstärkte Stiefel', 'boots', 'common', 1, 1, 1, 0, 115, NULL),
('Gemeine Stiefel', 'boots', 'common', 1, 1, 0, 1, 100, NULL),
('Braune Stiefel', 'boots', 'common', 0, 1, 2, 0, 125, NULL),
('Schwarze Stiefel', 'boots', 'common', 1, 2, 0, 0, 110, NULL),
('Graue Stiefel', 'boots', 'common', 1, 0, 1, 1, 100, NULL),
('Robuste Stiefel', 'boots', 'common', 0, 1, 2, 0, 135, NULL),
('Leichte Stiefel', 'boots', 'common', 0, 3, 0, 0, 90, NULL),
('Feste Stiefel', 'boots', 'common', 2, 0, 1, 0, 130, NULL),
('Alte Stiefel', 'boots', 'common', 1, 1, 1, 0, 80, NULL),
('Neue Stiefel', 'boots', 'common', 1, 2, 1, 0, 120, NULL),
('Warme Stiefel', 'boots', 'common', 0, 1, 2, 0, 125, NULL),
('Kalte Stiefel', 'boots', 'common', 1, 2, 0, 0, 105, NULL),

-- Rare Boots (20 items)
('Ritterstiefel', 'boots', 'rare', 3, 2, 2, 0, 300, 'Erhöht Kampfkraft um 5%'),
('Diebsstiefel', 'boots', 'rare', 1, 5, 1, 0, 280, 'Ermöglicht Schleichen'),
('Magische Stiefel', 'boots', 'rare', 0, 2, 1, 4, 320, 'Mana Regeneration +10%'),
('Berserker Stiefel', 'boots', 'rare', 4, 1, 2, 0, 350, 'Wut-Modus verfügbar'),
('Elfenstiefel', 'boots', 'rare', 1, 4, 1, 1, 290, 'Naturverbundenheit'),
('Zwergen Stiefel', 'boots', 'rare', 3, 1, 3, 0, 330, 'Bergbau Bonus +20%'),
('Assassinen Stiefel', 'boots', 'rare', 2, 4, 1, 0, 340, 'Kritische Treffer +15%'),
('Paladinstiefel', 'boots', 'rare', 2, 1, 3, 1, 360, 'Heilung +10%'),
('Schamanen Stiefel', 'boots', 'rare', 1, 2, 2, 2, 310, 'Geisterbeschwörung'),
('Barbaren Stiefel', 'boots', 'rare', 4, 2, 1, 0, 320, 'Wilde Angriffe'),
('Waldläufer Stiefel', 'boots', 'rare', 2, 3, 1, 1, 300, 'Spurenlesen'),
('Krieger Stiefel', 'boots', 'rare', 3, 1, 3, 0, 340, 'Blockchance +20%'),
('Hexer Stiefel', 'boots', 'rare', 1, 2, 1, 3, 320, 'Zauberresistenz +15%'),
('Mönch Stiefel', 'boots', 'rare', 2, 3, 2, 0, 280, 'Meditation verfügbar'),
('Nekromant Stiefel', 'boots', 'rare', 0, 1, 2, 4, 350, 'Untote beschwören'),
('Gladiator Stiefel', 'boots', 'rare', 3, 2, 2, 0, 330, 'Arena Kampf +25%'),
('Jäger Stiefel', 'boots', 'rare', 2, 4, 1, 0, 290, 'Tierfreund'),
('Pirat Stiefel', 'boots', 'rare', 2, 3, 1, 1, 310, 'Seekrankheit Immunität'),
('Rogue Stiefel', 'boots', 'rare', 1, 4, 1, 1, 300, 'Taschendiebstahl'),
('Vampire Stiefel', 'boots', 'rare', 2, 2, 1, 2, 340, 'Lebensraub +10%'),

-- Epic Boots (8 items)
('Drachenstiefel', 'boots', 'epic', 5, 3, 4, 2, 800, 'Feuerimmunität, Flugfähigkeit'),
('Phoenixstiefel', 'boots', 'epic', 3, 4, 3, 4, 850, 'Wiedergeburt bei Tod'),
('Titanstiefel', 'boots', 'epic', 6, 2, 5, 1, 900, 'Unzerstörbar'),
('Schattenstiefel', 'boots', 'epic', 2, 6, 2, 3, 750, 'Unsichtbarkeit'),
('Blitzstiefel', 'boots', 'epic', 3, 7, 2, 2, 820, 'Teleportation'),
('Kristallstiefel', 'boots', 'epic', 4, 3, 3, 4, 880, 'Manareflexion'),
('Götter Stiefel', 'boots', 'epic', 5, 4, 4, 3, 950, 'Göttlicher Schutz'),
('Chaos Stiefel', 'boots', 'epic', 4, 5, 3, 3, 870, 'Zufällige Magie'),

-- Legendary Boots (2 items)
('Stiefel der Ewigkeit', 'boots', 'legendary', 8, 6, 6, 5, 2000, 'Unsterblichkeit, Zeitkontrolle'),
('Allmächtige Stiefel', 'boots', 'legendary', 10, 8, 8, 7, 2500, 'Realitätsverzerrung');

-- Pants (50 items)
INSERT INTO items (name, type, rarity, strength_bonus, agility_bonus, vitality_bonus, intelligence_bonus, value, special_effect) VALUES
-- Common Pants (20 items)
('Lederhose', 'pants', 'common', 1, 1, 2, 0, 120, NULL),
('Stoffhose', 'pants', 'common', 0, 2, 1, 1, 100, NULL),
('Kampfhose', 'pants', 'common', 2, 0, 2, 0, 140, NULL),
('Laufhose', 'pants', 'common', 0, 3, 1, 0, 110, NULL),
('Arbeitshose', 'pants', 'common', 1, 0, 3, 0, 150, NULL),
('Baumwollhose', 'pants', 'common', 0, 1, 1, 2, 105, NULL),
('Eisenhose', 'pants', 'common', 2, 0, 3, 0, 160, NULL),
('Schnellhose', 'pants', 'common', 0, 2, 2, 0, 115, NULL),
('Verstärkte Hose', 'pants', 'common', 1, 1, 2, 0, 125, NULL),
('Gemeine Hose', 'pants', 'common', 1, 1, 1, 1, 110, NULL),
('Braune Hose', 'pants', 'common', 0, 1, 3, 0, 135, NULL),
('Schwarze Hose', 'pants', 'common', 1, 2, 1, 0, 120, NULL),
('Graue Hose', 'pants', 'common', 1, 0, 2, 1, 110, NULL),
('Robuste Hose', 'pants', 'common', 0, 1, 3, 0, 145, NULL),
('Leichte Hose', 'pants', 'common', 0, 3, 1, 0, 100, NULL),
('Feste Hose', 'pants', 'common', 2, 0, 2, 0, 140, NULL),
('Alte Hose', 'pants', 'common', 1, 1, 2, 0, 90, NULL),
('Neue Hose', 'pants', 'common', 1, 2, 2, 0, 130, NULL),
('Warme Hose', 'pants', 'common', 0, 1, 3, 0, 135, NULL),
('Kalte Hose', 'pants', 'common', 1, 2, 1, 0, 115, NULL),

-- Rare Pants (20 items)
('Ritterhose', 'pants', 'rare', 3, 1, 4, 0, 350, 'Rüstung +15%'),
('Diebshose', 'pants', 'rare', 1, 4, 2, 0, 320, 'Bewegung lautlos'),
('Magische Hose', 'pants', 'rare', 0, 2, 2, 4, 370, 'Zauberresistenz +20%'),
('Berserker Hose', 'pants', 'rare', 4, 1, 3, 0, 400, 'Kampfrausch'),
('Elfenhose', 'pants', 'rare', 1, 3, 2, 2, 340, 'Naturschutz'),
('Zwergen Hose', 'pants', 'rare', 3, 1, 4, 0, 380, 'Felsenfest'),
('Assassinen Hose', 'pants', 'rare', 2, 4, 2, 0, 390, 'Giftresistenz'),
('Paladinhose', 'pants', 'rare', 2, 1, 4, 1, 410, 'Lichtaura'),
('Schamanen Hose', 'pants', 'rare', 1, 2, 3, 2, 360, 'Elementarschutz'),
('Barbaren Hose', 'pants', 'rare', 4, 2, 2, 0, 370, 'Wilde Kraft'),
('Waldläufer Hose', 'pants', 'rare', 2, 3, 2, 1, 350, 'Tiersprache'),
('Krieger Hose', 'pants', 'rare', 3, 1, 4, 0, 390, 'Standhaftigkeit'),
('Hexer Hose', 'pants', 'rare', 1, 2, 2, 3, 370, 'Fluchschutz'),
('Mönch Hose', 'pants', 'rare', 2, 3, 3, 0, 330, 'Innere Ruhe'),
('Nekromant Hose', 'pants', 'rare', 0, 1, 3, 4, 400, 'Todesresistenz'),
('Gladiator Hose', 'pants', 'rare', 3, 2, 3, 0, 380, 'Kampfgeist'),
('Jäger Hose', 'pants', 'rare', 2, 4, 2, 0, 340, 'Tarnung'),
('Pirat Hose', 'pants', 'rare', 2, 3, 2, 1, 360, 'Wasserresistenz'),
('Rogue Hose', 'pants', 'rare', 1, 4, 2, 1, 350, 'Flinke Finger'),
('Vampire Hose', 'pants', 'rare', 2, 2, 2, 2, 390, 'Blutdurst'),

-- Epic Pants (8 items)
('Drachenhose', 'pants', 'epic', 5, 2, 6, 2, 900, 'Feuerschutz, Drachenkraft'),
('Phoenixhose', 'pants', 'epic', 3, 3, 5, 4, 950, 'Regeneration +50%'),
('Titanhose', 'pants', 'epic', 6, 1, 7, 1, 1000, 'Unverwundbarkeit'),
('Schattenhose', 'pants', 'epic', 2, 5, 3, 4, 850, 'Schattengang'),
('Blitzhose', 'pants', 'epic', 3, 6, 4, 2, 920, 'Blitzgeschwindigkeit'),
('Kristallhose', 'pants', 'epic', 4, 2, 5, 4, 980, 'Kristallrüstung'),
('Götter Hose', 'pants', 'epic', 5, 3, 6, 3, 1050, 'Göttliche Macht'),
('Chaos Hose', 'pants', 'epic', 4, 4, 4, 4, 970, 'Chaosenergie'),

-- Legendary Pants (2 items)
('Hose der Ewigkeit', 'pants', 'legendary', 8, 5, 9, 6, 2200, 'Ewige Ausdauer'),
('Allmächtige Hose', 'pants', 'legendary', 10, 7, 11, 8, 2700, 'Absolute Macht');

-- Armor (50 items)
INSERT INTO items (name, type, rarity, strength_bonus, agility_bonus, vitality_bonus, intelligence_bonus, value, special_effect) VALUES
-- Common Armor (20 items)
('Lederrüstung', 'armor', 'common', 2, 1, 3, 0, 200, NULL),
('Stoffrobe', 'armor', 'common', 0, 1, 2, 3, 180, NULL),
('Kettenhemd', 'armor', 'common', 3, 0, 4, 0, 250, NULL),
('Laufweste', 'armor', 'common', 1, 3, 2, 0, 190, NULL),
('Arbeitshemd', 'armor', 'common', 2, 0, 4, 0, 220, NULL),
('Baumwollhemd', 'armor', 'common', 0, 2, 2, 2, 170, NULL),
('Eisenrüstung', 'armor', 'common', 4, 0, 5, 0, 280, NULL),
('Schnellweste', 'armor', 'common', 1, 3, 3, 0, 200, NULL),
('Verstärkte Rüstung', 'armor', 'common', 2, 1, 4, 0, 230, NULL),
('Gemeine Rüstung', 'armor', 'common', 2, 1, 3, 1, 190, NULL),
('Braune Rüstung', 'armor', 'common', 1, 2, 4, 0, 210, NULL),
('Schwarze Rüstung', 'armor', 'common', 3, 1, 3, 0, 220, NULL),
('Graue Rüstung', 'armor', 'common', 2, 1, 3, 1, 200, NULL),
('Robuste Rüstung', 'armor', 'common', 1, 0, 5, 0, 240, NULL),
('Leichte Rüstung', 'armor', 'common', 1, 4, 2, 0, 180, NULL),
('Feste Rüstung', 'armor', 'common', 3, 0, 4, 0, 250, NULL),
('Alte Rüstung', 'armor', 'common', 2, 1, 3, 0, 160, NULL),
('Neue Rüstung', 'armor', 'common', 2, 2, 3, 0, 210, NULL),
('Warme Rüstung', 'armor', 'common', 1, 1, 4, 0, 220, NULL),
('Kalte Rüstung', 'armor', 'common', 2, 2, 2, 0, 190, NULL),

-- Rare Armor (20 items)
('Ritterrüstung', 'armor', 'rare', 5, 1, 6, 0, 600, 'Ehre +25%'),
('Diebsweste', 'armor', 'rare', 2, 5, 3, 0, 550, 'Verborgen bleiben'),
('Magiermantel', 'armor', 'rare', 1, 2, 3, 6, 650, 'Magieschutz +30%'),
('Berserkerrüstung', 'armor', 'rare', 6, 1, 5, 0, 700, 'Wilde Wut'),
('Elfenrüstung', 'armor', 'rare', 2, 4, 3, 3, 580, 'Waldverbindung'),
('Zwergen Rüstung', 'armor', 'rare', 5, 1, 7, 0, 680, 'Unerschütterlich'),
('Assassinenrüstung', 'armor', 'rare', 3, 5, 3, 0, 670, 'Lautlose Bewegung'),
('Paladinrüstung', 'armor', 'rare', 4, 1, 6, 2, 720, 'Heiliges Licht'),
('Schamanenrüstung', 'armor', 'rare', 2, 3, 4, 3, 620, 'Elementarbindung'),
('Barbarenrüstung', 'armor', 'rare', 6, 2, 4, 0, 650, 'Primaler Zorn'),
('Waldläuferrüstung', 'armor', 'rare', 3, 4, 3, 2, 600, 'Naturharmonie'),
('Kriegerrüstung', 'armor', 'rare', 5, 1, 6, 0, 680, 'Unbeugsam'),
('Hexerrüstung', 'armor', 'rare', 2, 2, 4, 4, 640, 'Dunkle Magie'),
('Mönchrobe', 'armor', 'rare', 3, 4, 4, 0, 560, 'Innerer Frieden'),
('Nekromantenwand', 'armor', 'rare', 1, 1, 5, 6, 700, 'Untote Kontrolle'),
('Gladiatorenrüstung', 'armor', 'rare', 5, 2, 5, 0, 660, 'Arena Meister'),
('Jägerrüstung', 'armor', 'rare', 3, 5, 3, 0, 580, 'Perfekte Jagd'),
('Piratenmantel', 'armor', 'rare', 3, 4, 3, 2, 620, 'Seefahrerglück'),
('Rogue Weste', 'armor', 'rare', 2, 5, 3, 2, 600, 'Meisterdieb'),
('Vampirrüstung', 'armor', 'rare', 3, 3, 3, 3, 680, 'Blutsauger'),

-- Epic Armor (8 items)
('Drachenrüstung', 'armor', 'epic', 8, 3, 9, 3, 1500, 'Drachenmacht, Feuerimmunität'),
('Phoenixrobe', 'armor', 'epic', 5, 4, 7, 6, 1600, 'Wiedergeburt, Heilung +100%'),
('Titanrüstung', 'armor', 'epic', 10, 1, 12, 1, 1800, 'Unzerstörbar, Reflektion'),
('Schattenrüstung', 'armor', 'epic', 4, 8, 5, 6, 1400, 'Schattenform, Unsichtbarkeit'),
('Blitzrüstung', 'armor', 'epic', 6, 9, 6, 4, 1550, 'Blitzschnell, Teleport'),
('Kristallrüstung', 'armor', 'epic', 7, 3, 8, 7, 1650, 'Kristallbarriere, Magiereflexion'),
('Götterrüstung', 'armor', 'epic', 8, 4, 9, 5, 1750, 'Göttlicher Schutz, Segnung'),
('Chaosrüstung', 'armor', 'epic', 6, 6, 6, 6, 1600, 'Chaosenergie, Realitätsverzerrung'),

-- Legendary Armor (2 items)
('Rüstung der Ewigkeit', 'armor', 'legendary', 12, 7, 15, 8, 3500, 'Unsterblichkeit, Zeitkontrolle, Absolute Verteidigung'),
('Allmächtige Rüstung', 'armor', 'legendary', 15, 10, 18, 12, 4500, 'Göttliche Macht, Realitätsmanipulation, Unendliche Energie');

-- Helmet (50 items)
INSERT INTO items (name, type, rarity, strength_bonus, agility_bonus, vitality_bonus, intelligence_bonus, value, special_effect) VALUES
-- Common Helmet (20 items)
('Lederhelm', 'helmet', 'common', 1, 1, 2, 0, 80, NULL),
('Stoffmütze', 'helmet', 'common', 0, 1, 1, 2, 70, NULL),
('Eisenhelm', 'helmet', 'common', 2, 0, 3, 0, 100, NULL),
('Laufkappe', 'helmet', 'common', 0, 2, 1, 0, 75, NULL),
('Arbeitshelm', 'helmet', 'common', 1, 0, 3, 0, 90, NULL),
('Baumwollhut', 'helmet', 'common', 0, 1, 1, 2, 65, NULL),
('Kampfhelm', 'helmet', 'common', 2, 0, 2, 0, 95, NULL),
('Schnellhelm', 'helmet', 'common', 0, 2, 1, 0, 80, NULL),
('Verstärkter Helm', 'helmet', 'common', 1, 1, 2, 0, 85, NULL),
('Gemeiner Helm', 'helmet', 'common', 1, 1, 1, 1, 75, NULL),
('Brauner Helm', 'helmet', 'common', 0, 1, 2, 0, 85, NULL),
('Schwarzer Helm', 'helmet', 'common', 1, 1, 1, 0, 80, NULL),
('Grauer Helm', 'helmet', 'common', 1, 0, 2, 1, 75, NULL),
('Robuster Helm', 'helmet', 'common', 0, 0, 3, 0, 95, NULL),
('Leichter Helm', 'helmet', 'common', 0, 2, 1, 0, 70, NULL),
('Fester Helm', 'helmet', 'common', 2, 0, 2, 0, 90, NULL),
('Alter Helm', 'helmet', 'common', 1, 1, 1, 0, 60, NULL),
('Neuer Helm', 'helmet', 'common', 1, 1, 2, 0, 85, NULL),
('Warmer Helm', 'helmet', 'common', 0, 1, 2, 0, 85, NULL),
('Kalter Helm', 'helmet', 'common', 1, 1, 1, 0, 75, NULL),

-- Rare Helmet (20 items)
('Ritterhelm', 'helmet', 'rare', 3, 1, 4, 0, 250, 'Tapferkeit +20%'),
('Diebsmaske', 'helmet', 'rare', 1, 4, 2, 0, 220, 'Verkleidung'),
('Zaubererhut', 'helmet', 'rare', 0, 2, 2, 4, 270, 'Weisheit +25%'),
('Berserkerhelm', 'helmet', 'rare', 4, 1, 3, 0, 300, 'Kampfwahn'),
('Elfenmaske', 'helmet', 'rare', 1, 3, 2, 2, 240, 'Natursicht'),
('Zwergenhelm', 'helmet', 'rare', 3, 1, 4, 0, 280, 'Felsenhaut'),
('Assassinenmask', 'helmet', 'rare', 2, 4, 2, 0, 290, 'Todesblick'),
('Paladinhelm', 'helmet', 'rare', 2, 1, 3, 2, 310, 'Göttliche Gnade'),
('Schamanenkrone', 'helmet', 'rare', 1, 2, 3, 2, 260, 'Geistersicht'),
('Barbarenhelm', 'helmet', 'rare', 4, 2, 2, 0, 270, 'Wilde Instinkte'),
('Waldläuferkappe', 'helmet', 'rare', 2, 3, 2, 1, 250, 'Adleraugen'),
('Kriegerhelm', 'helmet', 'rare', 3, 1, 4, 0, 280, 'Standhaft'),
('Hexerhut', 'helmet', 'rare', 1, 2, 2, 3, 270, 'Dunkle Visionen'),
('Mönchmütze', 'helmet', 'rare', 2, 3, 2, 0, 230, 'Erleuchtung'),
('Nekromantenkrone', 'helmet', 'rare', 0, 1, 3, 4, 300, 'Todesblick'),
('Gladiatorhelm', 'helmet', 'rare', 3, 2, 3, 0, 280, 'Kampfgeist'),
('Jägermaske', 'helmet', 'rare', 2, 4, 2, 0, 240, 'Fährtenleser'),
('Piratenhut', 'helmet', 'rare', 2, 3, 2, 1, 260, 'Sturmresistenz'),
('Rogue Maske', 'helmet', 'rare', 1, 4, 2, 1, 250, 'Schatten des Zweifels'),
('Vampirmaske', 'helmet', 'rare', 2, 2, 2, 2, 290, 'Blutgier'),

-- Epic Helmet (8 items)
('Drachenhelm', 'helmet', 'epic', 5, 2, 6, 2, 800, 'Drachensicht, Feueratem'),
('Phoenixkrone', 'helmet', 'epic', 3, 3, 4, 5, 850, 'Wiedergeburt, Heilung'),
('Titanhelm', 'helmet', 'epic', 6, 1, 7, 1, 950, 'Unbrechbar, Gedankenschutz'),
('Schattenmaske', 'helmet', 'epic', 2, 6, 3, 4, 750, 'Gedankenkontrolle'),
('Blitzhelm', 'helmet', 'epic', 3, 7, 4, 2, 820, 'Blitzdenken, Zeitlupe'),
('Kristallhelm', 'helmet', 'epic', 4, 2, 5, 6, 880, 'Kristallsicht, Zukunftsvision'),
('Götterhelm', 'helmet', 'epic', 5, 3, 6, 4, 1000, 'Göttliche Weisheit'),
('Chaoshelm', 'helmet', 'epic', 4, 4, 4, 4, 870, 'Chaosgedanken'),

-- Legendary Helmet (2 items)
('Krone der Ewigkeit', 'helmet', 'legendary', 8, 5, 9, 8, 2000, 'Allmacht, Zeitkontrolle, Universelles Wissen'),
('Allmächtige Krone', 'helmet', 'legendary', 10, 7, 11, 12, 2500, 'Absolute Herrschaft, Realitätskontrolle');

-- Ring (50 items)
INSERT INTO items (name, type, rarity, strength_bonus, agility_bonus, vitality_bonus, intelligence_bonus, value, special_effect) VALUES
-- Common Ring (20 items)
('Eisenring', 'ring', 'common', 1, 0, 1, 0, 50, NULL),
('Kupferring', 'ring', 'common', 0, 1, 0, 1, 45, NULL),
('Silberring', 'ring', 'common', 0, 1, 1, 0, 60, NULL),
('Bronzering', 'ring', 'common', 1, 0, 0, 1, 50, NULL),
('Holzring', 'ring', 'common', 0, 0, 1, 1, 40, NULL),
('Steinring', 'ring', 'common', 1, 0, 1, 0, 55, NULL),
('Lederring', 'ring', 'common', 0, 1, 1, 0, 45, NULL),
('Knochenring', 'ring', 'common', 1, 1, 0, 0, 50, NULL),
('Glasring', 'ring', 'common', 0, 0, 0, 2, 40, NULL),
('Wachsring', 'ring', 'common', 0, 1, 0, 1, 35, NULL),
('Stoffring', 'ring', 'common', 0, 0, 1, 1, 40, NULL),
('Sandring', 'ring', 'common', 0, 1, 0, 1, 35, NULL),
('Tonring', 'ring', 'common', 1, 0, 1, 0, 45, NULL),
('Bambusring', 'ring', 'common', 0, 1, 1, 0, 40, NULL),
('Korkring', 'ring', 'common', 0, 0, 1, 1, 35, NULL),
('Gummiring', 'ring', 'common', 0, 1, 0, 1, 40, NULL),
('Plastikring', 'ring', 'common', 0, 0, 1, 1, 30, NULL),
('Aluminiumring', 'ring', 'common', 1, 1, 0, 0, 50, NULL),
('Bleiring', 'ring', 'common', 1, 0, 1, 0, 45, NULL),
('Zinnring', 'ring', 'common', 0, 1, 0, 1, 45, NULL),

-- Rare Ring (20 items)
('Goldring', 'ring', 'rare', 2, 2, 2, 2, 200, 'Glück +10%'),
('Rubin Ring', 'ring', 'rare', 3, 1, 2, 1, 250, 'Feuerschutz'),
('Saphir Ring', 'ring', 'rare', 1, 2, 2, 2, 240, 'Wasserschutz'),
('Smaragd Ring', 'ring', 'rare', 1, 2, 1, 3, 230, 'Naturkraft'),
('Diamant Ring', 'ring', 'rare', 2, 2, 2, 2, 300, 'Unzerbrechlich'),
('Opal Ring', 'ring', 'rare', 1, 3, 1, 2, 220, 'Illusion'),
('Amethyst Ring', 'ring', 'rare', 1, 1, 2, 3, 210, 'Geistklarheit'),
('Topas Ring', 'ring', 'rare', 2, 2, 1, 2, 230, 'Sonnenenergie'),
('Onyx Ring', 'ring', 'rare', 3, 1, 3, 0, 240, 'Schutz vor Flüchen'),
('Perlen Ring', 'ring', 'rare', 1, 1, 3, 2, 220, 'Meeresschutz'),
('Türkis Ring', 'ring', 'rare', 1, 2, 2, 2, 210, 'Heilung +15%'),
('Jade Ring', 'ring', 'rare', 2, 2, 3, 0, 250, 'Langlebigkeit'),
('Granat Ring', 'ring', 'rare', 3, 2, 1, 1, 240, 'Kampfgeist'),
('Aquamarin Ring', 'ring', 'rare', 1, 2, 1, 3, 230, 'Meeresmagie'),
('Citrin Ring', 'ring', 'rare', 2, 1, 2, 2, 220, 'Positive Energie'),
('Mondstein Ring', 'ring', 'rare', 1, 3, 1, 2, 240, 'Mondkraft'),
('Sonnenstein Ring', 'ring', 'rare', 3, 1, 2, 1, 250, 'Sonnenkraft'),
('Obsidian Ring', 'ring', 'rare', 2, 1, 2, 2, 230, 'Vulkanmacht'),
('Kristall Ring', 'ring', 'rare', 1, 1, 1, 4, 260, 'Kristallenergie'),
('Meteorit Ring', 'ring', 'rare', 2, 2, 2, 2, 280, 'Sternenkraft'),

-- Epic Ring (8 items)
('Drachenring', 'ring', 'epic', 4, 3, 4, 3, 600, 'Drachenkraft, Feuermagie'),
('Phoenixring', 'ring', 'epic', 3, 4, 3, 4, 650, 'Wiedergeburt, Heilmagie'),
('Titanring', 'ring', 'epic', 5, 2, 5, 2, 700, 'Unzerstörbarkeit'),
('Schattenring', 'ring', 'epic', 2, 5, 2, 5, 550, 'Schattenmagie'),
('Blitzring', 'ring', 'epic', 3, 6, 3, 3, 620, 'Blitzmagie'),
('Kristallring', 'ring', 'epic', 3, 3, 3, 6, 680, 'Kristallmagie'),
('Götterring', 'ring', 'epic', 4, 4, 4, 4, 750, 'Göttliche Kraft'),
('Chaosring', 'ring', 'epic', 4, 4, 4, 4, 670, 'Chaosmagie'),

-- Legendary Ring (2 items)
('Ring der Ewigkeit', 'ring', 'legendary', 6, 6, 6, 8, 1500, 'Ewige Macht, Zeitkontrolle'),
('Allmächtiger Ring', 'ring', 'legendary', 8, 8, 8, 10, 2000, 'Universelle Kontrolle');

-- Chain (50 items)
INSERT INTO items (name, type, rarity, strength_bonus, agility_bonus, vitality_bonus, intelligence_bonus, value, special_effect) VALUES
-- Common Chain (20 items)
('Eisenkette', 'chain', 'common', 1, 0, 1, 0, 60, NULL),
('Kupferkette', 'chain', 'common', 0, 1, 0, 1, 55, NULL),
('Silberkette', 'chain', 'common', 0, 1, 1, 0, 70, NULL),
('Bronzekette', 'chain', 'common', 1, 0, 0, 1, 60, NULL),
('Lederkette', 'chain', 'common', 0, 1, 1, 0, 50, NULL),
('Seilkette', 'chain', 'common', 0, 0, 1, 1, 45, NULL),
('Stoffkette', 'chain', 'common', 0, 0, 1, 1, 40, NULL),
('Knochenkette', 'chain', 'common', 1, 1, 0, 0, 55, NULL),
('Holzkette', 'chain', 'common', 0, 0, 1, 1, 45, NULL),
('Steinkette', 'chain', 'common', 1, 0, 1, 0, 65, NULL),
('Perlenkette', 'chain', 'common', 0, 1, 1, 0, 60, NULL),
('Muschelkette', 'chain', 'common', 0, 0, 1, 1, 50, NULL),
('Federkette', 'chain', 'common', 0, 1, 0, 1, 45, NULL),
('Blätterkette', 'chain', 'common', 0, 0, 1, 1, 40, NULL),
('Samenkette', 'chain', 'common', 0, 1, 1, 0, 45, NULL),
('Blütenkette', 'chain', 'common', 0, 0, 0, 2, 40, NULL),
('Kristallkette', 'chain', 'common', 0, 0, 1, 1, 55, NULL),
('Glaskette', 'chain', 'common', 0, 0, 0, 2, 35, NULL),
('Bernsteinkette', 'chain', 'common', 0, 1, 0, 1, 50, NULL),
('Koralenkette', 'chain', 'common', 0, 0, 1, 1, 50, NULL),

-- Rare Chain (20 items)
('Goldkette', 'chain', 'rare', 2, 2, 2, 2, 300, 'Reichtum +15%'),
('Rubinkette', 'chain', 'rare', 3, 1, 2, 1, 350, 'Feuerresistenz'),
('Saphirkette', 'chain', 'rare', 1, 2, 2, 2, 340, 'Wasserresistenz'),
('Smaragdkette', 'chain', 'rare', 1, 2, 1, 3, 330, 'Naturverbindung'),
('Diamantkette', 'chain', 'rare', 2, 2, 2, 2, 400, 'Glück +20%'),
('Opalkette', 'chain', 'rare', 1, 3, 1, 2, 320, 'Traumkontrolle'),
('Amethystkette', 'chain', 'rare', 1, 1, 2, 3, 310, 'Geistige Klarheit'),
('Topaskette', 'chain', 'rare', 2, 2, 1, 2, 330, 'Lichtkraft'),
('Onyxkette', 'chain', 'rare', 3, 1, 3, 0, 340, 'Negativschutz'),
('Perlenkette des Meeres', 'chain', 'rare', 1, 1, 3, 2, 320, 'Unterwasseratmung'),
('Türkiskette', 'chain', 'rare', 1, 2, 2, 2, 310, 'Heilungsbonus'),
('Jadekette', 'chain', 'rare', 2, 2, 3, 0, 350, 'Ewige Jugend'),
('Granatkette', 'chain', 'rare', 3, 2, 1, 1, 340, 'Mut +25%'),
('Aquamarinkette', 'chain', 'rare', 1, 2, 1, 3, 330, 'Ozeanmagie'),
('Citrinkette', 'chain', 'rare', 2, 1, 2, 2, 320, 'Sonnenschutz'),
('Mondsteinkette', 'chain', 'rare', 1, 3, 1, 2, 340, 'Nachtmagie'),
('Sonnensteinkette', 'chain', 'rare', 3, 1, 2, 1, 350, 'Tagmagie'),
('Obsidiankette', 'chain', 'rare', 2, 1, 2, 2, 330, 'Vulkanschutz'),
('Kristallkette der Macht', 'chain', 'rare', 1, 1, 1, 4, 360, 'Manaregeneration'),
('Meteoritkette', 'chain', 'rare', 2, 2, 2, 2, 380, 'Kosmische Kraft'),

-- Epic Chain (8 items)
('Drachenkette', 'chain', 'epic', 4, 3, 4, 3, 800, 'Drachenbindung, Feuerkontrolle'),
('Phoenixkette', 'chain', 'epic', 3, 4, 3, 4, 850, 'Unsterblichkeit, Regeneration'),
('Titankette', 'chain', 'epic', 5, 2, 5, 2, 900, 'Titanenstärke'),
('Schattenkette', 'chain', 'epic', 2, 5, 2, 5, 750, 'Schattenbindung'),
('Blitzkette', 'chain', 'epic', 3, 6, 3, 3, 820, 'Blitzkontrolle'),
('Kristallkette der Götter', 'chain', 'epic', 3, 3, 3, 6, 880, 'Kristallmacht'),
('Götterkette', 'chain', 'epic', 4, 4, 4, 4, 950, 'Göttlicher Schutz'),
('Chaoskette', 'chain', 'epic', 4, 4, 4, 4, 870, 'Chaoskontrolle'),

-- Legendary Chain (2 items)
('Kette der Ewigkeit', 'chain', 'legendary', 6, 6, 6, 8, 2000, 'Ewigkeitsbindung, Zeitmanipulation'),
('Allmächtige Kette', 'chain', 'legendary', 8, 8, 8, 10, 2500, 'Absolute Kontrolle, Universelle Macht');